# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys4 ddr.xdc

# IP: ip/floating_point_div/floating_point_div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_div || ORIG_REF_NAME==floating_point_div} -quiet] -quiet
