# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.cache/wt [current_project]
set_property parent.project_path D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/CCodeToOCode.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/add_32bit_SFIX.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/cos_32bit_SFIX.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/div_32bit_SFIX.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/fix_to_float_32bit.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/math_3D.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/matrix_apply.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/matrix_mul.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/mul_32bit_SFIX.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/sin_32bit_SFIX.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/sub_32bit_SFIX.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/vector_dotproduct.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/vga1024x768.v
  D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/VGA_RAM.v
}
read_ip -quiet D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/floating_point_div/floating_point_div.xci
set_property used_in_implementation false [get_files -all d:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/floating_point_div/floating_point_div_ooc.xdc]

read_ip -quiet D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/cordic_sin/cordic_sin.xci

read_ip -quiet D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
set_property used_in_implementation false [get_files -all d:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc]

read_ip -quiet D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
set_property used_in_implementation false [get_files -all d:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/constrs_1/new/Nexys4 ddr.xdc}}
set_property used_in_implementation false [get_files {{D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/constrs_1/new/Nexys4 ddr.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top VGA_RAM -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef VGA_RAM.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file VGA_RAM_utilization_synth.rpt -pb VGA_RAM_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
