# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.runs/synth_1/.Xil/Vivado-5892-DESKTOP/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog {
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.runs/synth_1/.Xil/Vivado-5892-DESKTOP/realtime/floating_point_div_stub.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.runs/synth_1/.Xil/Vivado-5892-DESKTOP/realtime/blk_mem_gen_0_stub.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.runs/synth_1/.Xil/Vivado-5892-DESKTOP/realtime/cordic_sin_stub.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.runs/synth_1/.Xil/Vivado-5892-DESKTOP/realtime/floating_point_0_stub.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.runs/synth_1/.Xil/Vivado-5892-DESKTOP/realtime/floating_point_1_stub.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/CCodeToOCode.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/add_32bit_SFIX.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/cos_32bit_SFIX.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/div_32bit_SFIX.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/fix_to_float_32bit.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/math_3D.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/matrix_apply.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/matrix_mul.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/mul_32bit_SFIX.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/sin_32bit_SFIX.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/sub_32bit_SFIX.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/vector_dotproduct.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/vga1024x768.v
      D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.srcs/sources_1/new/VGA_RAM.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top VGA_RAM
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/codehub/VIVADO/VGA_RAM_try2/VGA_RAM_try1.runs/synth_1/.Xil/Vivado-5892-DESKTOP/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
